export { default as PostRegister } from 'board/components/PostRegister'
export { default as PostList } from 'board/components/PostList'
export { default as PostDelete } from 'board/components/PostDelete'
export { default as PostRetrieve } from 'board/components/PostRetrieve'
export { default as PostUpdate } from 'board/components/PostUpdate'